/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = bigint;
export interface FileAttachment {
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'fileId' : string,
}
export interface FriendRequest {
  'to' : UserId,
  'status' : FriendStatus,
  'from' : UserId,
  'timestamp' : Timestamp,
}
export type FriendStatus = { 'Rejected' : null } |
  { 'Accepted' : null } |
  { 'Pending' : null };
export type Language = string;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'fileAttachment' : [] | [FileAttachment],
  'timestamp' : Timestamp,
  'reactions' : Array<Reaction>,
}
export type MessageId = bigint;
export type PresenceStatus = { 'Away' : null } |
  { 'Online' : null } |
  { 'Offline' : null };
export interface Reaction {
  'messageId' : MessageId,
  'userId' : UserId,
  'emoji' : string,
  'timestamp' : Timestamp,
}
export type Theme = string;
export type Timestamp = bigint;
export interface User { 'principal' : UserId, 'displayName' : string }
export type UserId = Principal;
export interface UserPreferences {
  'theme' : Theme,
  'language' : Language,
  'pinHash' : [] | [string],
}
export interface _SERVICE {
  'addReaction' : ActorMethod<
    [MessageId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getBulkPresence' : ActorMethod<
    [Array<UserId>],
    Array<[UserId, PresenceStatus]>
  >,
  'getCurrentUser' : ActorMethod<[], [] | [User]>,
  'getMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'getOrCreateConversation' : ActorMethod<[UserId], ConversationId>,
  'getPresence' : ActorMethod<[UserId], [] | [PresenceStatus]>,
  'getReactions' : ActorMethod<
    [MessageId],
    { 'ok' : Array<Reaction> } |
      { 'err' : string }
  >,
  'getTypingIndicators' : ActorMethod<[ConversationId], Array<UserId>>,
  'getUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'listFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'listFriends' : ActorMethod<[], Array<User>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'registerUser' : ActorMethod<[string], undefined>,
  'removeFriend' : ActorMethod<[UserId], { 'ok' : null } | { 'err' : string }>,
  'removeReaction' : ActorMethod<
    [MessageId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'respondToFriendRequest' : ActorMethod<
    [UserId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendFileMessage' : ActorMethod<
    [ConversationId, string, string, string, bigint],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'sendFriendRequest' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<[ConversationId, string], MessageId>,
  'setPresence' : ActorMethod<[PresenceStatus], undefined>,
  'setTyping' : ActorMethod<[ConversationId, boolean], undefined>,
  'setUserPreferences' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];