/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageId = IDL.Nat;
export const UserId = IDL.Principal;
export const PresenceStatus = IDL.Variant({
  'Away' : IDL.Null,
  'Online' : IDL.Null,
  'Offline' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
});
export const ConversationId = IDL.Nat;
export const FileAttachment = IDL.Record({
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'fileId' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Reaction = IDL.Record({
  'messageId' : MessageId,
  'userId' : UserId,
  'emoji' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'fileAttachment' : IDL.Opt(FileAttachment),
  'timestamp' : Timestamp,
  'reactions' : IDL.Vec(Reaction),
});
export const Theme = IDL.Text;
export const Language = IDL.Text;
export const UserPreferences = IDL.Record({
  'theme' : Theme,
  'language' : Language,
  'pinHash' : IDL.Opt(IDL.Text),
});
export const FriendStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'to' : UserId,
  'status' : FriendStatus,
  'from' : UserId,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'addReaction' : IDL.Func(
      [MessageId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getBulkPresence' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(IDL.Tuple(UserId, PresenceStatus))],
      ['query'],
    ),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], []),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
  'getPresence' : IDL.Func([UserId], [IDL.Opt(PresenceStatus)], ['query']),
  'getReactions' : IDL.Func(
      [MessageId],
      [IDL.Variant({ 'ok' : IDL.Vec(Reaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getTypingIndicators' : IDL.Func(
      [ConversationId],
      [IDL.Vec(UserId)],
      ['query'],
    ),
  'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'listFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'listFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'removeFriend' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeReaction' : IDL.Func(
      [MessageId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'respondToFriendRequest' : IDL.Func(
      [UserId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendFileMessage' : IDL.Func(
      [ConversationId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'sendFriendRequest' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
  'setPresence' : IDL.Func([PresenceStatus], [], []),
  'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
  'setUserPreferences' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageId = IDL.Nat;
  const UserId = IDL.Principal;
  const PresenceStatus = IDL.Variant({
    'Away' : IDL.Null,
    'Online' : IDL.Null,
    'Offline' : IDL.Null,
  });
  const User = IDL.Record({ 'principal' : UserId, 'displayName' : IDL.Text });
  const ConversationId = IDL.Nat;
  const FileAttachment = IDL.Record({
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'fileId' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Reaction = IDL.Record({
    'messageId' : MessageId,
    'userId' : UserId,
    'emoji' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : UserId,
    'conversationId' : ConversationId,
    'fileAttachment' : IDL.Opt(FileAttachment),
    'timestamp' : Timestamp,
    'reactions' : IDL.Vec(Reaction),
  });
  const Theme = IDL.Text;
  const Language = IDL.Text;
  const UserPreferences = IDL.Record({
    'theme' : Theme,
    'language' : Language,
    'pinHash' : IDL.Opt(IDL.Text),
  });
  const FriendStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'to' : UserId,
    'status' : FriendStatus,
    'from' : UserId,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'addReaction' : IDL.Func(
        [MessageId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getBulkPresence' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(IDL.Tuple(UserId, PresenceStatus))],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], []),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
    'getPresence' : IDL.Func([UserId], [IDL.Opt(PresenceStatus)], ['query']),
    'getReactions' : IDL.Func(
        [MessageId],
        [IDL.Variant({ 'ok' : IDL.Vec(Reaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getTypingIndicators' : IDL.Func(
        [ConversationId],
        [IDL.Vec(UserId)],
        ['query'],
      ),
    'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'listFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'listFriends' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'removeFriend' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeReaction' : IDL.Func(
        [MessageId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'respondToFriendRequest' : IDL.Func(
        [UserId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendFileMessage' : IDL.Func(
        [ConversationId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'sendFriendRequest' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [MessageId], []),
    'setPresence' : IDL.Func([PresenceStatus], [], []),
    'setTyping' : IDL.Func([ConversationId, IDL.Bool], [], []),
    'setUserPreferences' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };