/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    theme: Theme;
    language: Language;
    pinHash?: string;
}
export type Timestamp = bigint;
export interface User {
    principal: UserId;
    displayName: string;
}
export type Language = string;
export type ConversationId = bigint;
export type UserId = Principal;
export interface FriendRequest {
    to: UserId;
    status: FriendStatus;
    from: UserId;
    timestamp: Timestamp;
}
export interface FileAttachment {
    size: bigint;
    mimeType: string;
    filename: string;
    fileId: string;
}
export type MessageId = bigint;
export interface Message {
    id: MessageId;
    content: string;
    sender: UserId;
    conversationId: ConversationId;
    fileAttachment?: FileAttachment;
    timestamp: Timestamp;
    reactions: Array<Reaction>;
}
export type Theme = string;
export interface Reaction {
    messageId: MessageId;
    userId: UserId;
    emoji: string;
    timestamp: Timestamp;
}
export enum FriendStatus {
    Rejected = "Rejected",
    Accepted = "Accepted",
    Pending = "Pending"
}
export enum PresenceStatus {
    Away = "Away",
    Online = "Online",
    Offline = "Offline"
}
export interface backendInterface {
    addReaction(messageId: MessageId, emoji: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getBulkPresence(userIds: Array<UserId>): Promise<Array<[UserId, PresenceStatus]>>;
    getCurrentUser(): Promise<User | null>;
    getMessages(conversationId: ConversationId): Promise<Array<Message>>;
    getOrCreateConversation(other: UserId): Promise<ConversationId>;
    getPresence(userId: UserId): Promise<PresenceStatus | null>;
    getReactions(messageId: MessageId): Promise<{
        __kind__: "ok";
        ok: Array<Reaction>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTypingIndicators(conversationId: ConversationId): Promise<Array<UserId>>;
    getUserPreferences(): Promise<UserPreferences | null>;
    listFriendRequests(): Promise<Array<FriendRequest>>;
    listFriends(): Promise<Array<User>>;
    listUsers(): Promise<Array<User>>;
    registerUser(displayName: string): Promise<void>;
    removeFriend(userId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeReaction(messageId: MessageId, emoji: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    respondToFriendRequest(from: UserId, accept: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendFileMessage(conversationId: ConversationId, fileId: string, filename: string, mimeType: string, size: bigint): Promise<{
        __kind__: "ok";
        ok: Message;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendFriendRequest(to: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendMessage(conversationId: ConversationId, content: string): Promise<MessageId>;
    setPresence(status: PresenceStatus): Promise<void>;
    setTyping(conversationId: ConversationId, isTyping: boolean): Promise<void>;
    setUserPreferences(theme: string, language: string, pinHash: string | null): Promise<void>;
}
import type { ConversationId as _ConversationId, FileAttachment as _FileAttachment, FriendRequest as _FriendRequest, FriendStatus as _FriendStatus, Language as _Language, Message as _Message, MessageId as _MessageId, PresenceStatus as _PresenceStatus, Reaction as _Reaction, Theme as _Theme, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReaction(arg0: MessageId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBulkPresence(arg0: Array<UserId>): Promise<Array<[UserId, PresenceStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBulkPresence(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBulkPresence(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: ConversationId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateConversation(arg0: UserId): Promise<ConversationId> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateConversation(arg0);
            return result;
        }
    }
    async getPresence(arg0: UserId): Promise<PresenceStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresence(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresence(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: MessageId): Promise<{
        __kind__: "ok";
        ok: Array<Reaction>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTypingIndicators(arg0: ConversationId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingIndicators(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingIndicators(arg0);
            return result;
        }
    }
    async getUserPreferences(): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFriendRequests();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFriendRequests();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFriends(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFriends();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async removeFriend(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeReaction(arg0: MessageId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToFriendRequest(arg0: UserId, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToFriendRequest(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToFriendRequest(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFileMessage(arg0: ConversationId, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: Message;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFileMessage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFileMessage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: ConversationId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setPresence(arg0: PresenceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPresence(to_candid_PresenceStatus_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPresence(to_candid_PresenceStatus_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTyping(arg0: ConversationId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTyping(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTyping(arg0, arg1);
            return result;
        }
    }
    async setUserPreferences(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPreferences(arg0, arg1, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPreferences(arg0, arg1, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_FriendRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FriendStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendStatus): FriendStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PresenceStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PresenceStatus): PresenceStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileAttachment]): FileAttachment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PresenceStatus]): PresenceStatus | null {
    return value.length === 0 ? null : from_candid_PresenceStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : from_candid_UserPreferences_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    language: _Language;
    pinHash: [] | [string];
}): {
    theme: Theme;
    language: Language;
    pinHash?: string;
} {
    return {
        theme: value.theme,
        language: value.language,
        pinHash: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pinHash))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _UserId;
    status: _FriendStatus;
    from: _UserId;
    timestamp: _Timestamp;
}): {
    to: UserId;
    status: FriendStatus;
    from: UserId;
    timestamp: Timestamp;
} {
    return {
        to: value.to,
        status: from_candid_FriendStatus_n20(_uploadFile, _downloadFile, value.status),
        from: value.from,
        timestamp: value.timestamp
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    sender: _UserId;
    conversationId: _ConversationId;
    fileAttachment: [] | [_FileAttachment];
    timestamp: _Timestamp;
    reactions: Array<_Reaction>;
}): {
    id: MessageId;
    content: string;
    sender: UserId;
    conversationId: ConversationId;
    fileAttachment?: FileAttachment;
    timestamp: Timestamp;
    reactions: Array<Reaction>;
} {
    return {
        id: value.id,
        content: value.content,
        sender: value.sender,
        conversationId: value.conversationId,
        fileAttachment: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.fileAttachment)),
        timestamp: value.timestamp,
        reactions: value.reactions
    };
}
function from_candid_tuple_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _PresenceStatus]): [UserId, PresenceStatus] {
    return [
        value[0],
        from_candid_PresenceStatus_n4(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Reaction>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Reaction>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
}): FriendStatus {
    return "Rejected" in value ? FriendStatus.Rejected : "Accepted" in value ? FriendStatus.Accepted : "Pending" in value ? FriendStatus.Pending : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Message;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Message;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Message_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Away: null;
} | {
    Online: null;
} | {
    Offline: null;
}): PresenceStatus {
    return "Away" in value ? PresenceStatus.Away : "Online" in value ? PresenceStatus.Online : "Offline" in value ? PresenceStatus.Offline : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _PresenceStatus]>): Array<[UserId, PresenceStatus]> {
    return value.map((x)=>from_candid_tuple_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PresenceStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PresenceStatus): _PresenceStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PresenceStatus): {
    Away: null;
} | {
    Online: null;
} | {
    Offline: null;
} {
    return value == PresenceStatus.Away ? {
        Away: null
    } : value == PresenceStatus.Online ? {
        Online: null
    } : value == PresenceStatus.Offline ? {
        Offline: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
